### PR TITLE
[WIP] adapter for katipo

### PR DESCRIPTION
**Pull request by amatalai**
At the moment it works fine with osx, and ubuntu trusty. I could not make it work with other linux distros yet.

Let me know if you want to support adapters with such limitations. Maybe I should extract it to separate package tesla_katipo or something?

### CODE REVIEW

**Comment by teamon** [comment]
I'm cool with having this adapter in the main repo since we can have it compiled conditionally like hackney or ibrowse :)

What's the deal with `metrics` dependency?

**Comment by amatalai** [comment]
Conflict between hackney and katipo:
screen shot 2017-01-23 at 15 56 20
It cannot be merged in current state, because hex won't allow to publish it like this
```
mix hex.build
** (Mix) Can't build package with overridden dependency metrics, remove `override: true`
```

**Comment by amatalai** [comment]
I have found a workaround (see 23cf602)

Downsides:
- katipo won't be listed as optional dependency in hex
- publishing to hex would require:
```elixir
MIX_ENV=publish mix deps.unlock metrics
MIX_ENV=publish mix deps.get
MIX_ENV=publish mix hex.publish
```
ofc I could create script for this and alias it as `hex.publish` to make it less annoying but first I want to know what do you think about this

**Comment by teamon** [comment]
Hacking hex seems a bit dirty and I'm afraid it could lead to some confusion :|
Let's me ask around and see if there is some other way to do this (apart from creating a separate package for each adapter which I'd really like to avoid).

**Comment by amatalai** [comment]
Ok, it seems to be very rare problem. Maybe it's worth to create issue in hex repo.

**Comment by teamon** [comment]
Hey @amatalai any chance katipo has updated its dependencies?

**Comment by amatalai** [comment]
Hi, unfortunately the problem is that katipo use newer "metrics" than hackney

**Comment by amatalai** [comment]
I don't think it will be ever possible to resolve conflict between erlang packages. Closing it for now.

**Pull request closed without merging**
