### PR TITLE
Raise ArgumentError if multipart field is invalid.

### LINKED ISSUE #230: Requests hang forever when using integers as values in multipart
### Environment

`uname -a` output:
```
Linux hostname-pc 4.17.3-100.fc27.x86_64 #1 SMP Tue Jun 26 14:19:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
`elixir --version` output: 
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.2 (compiled with OTP 19)
```

### Current behavior

When passing a integer value as third argument to `add_field/4`, it never returns when executing the request:

```elixir
alias Tesla.Multipart
chat_id_int = -1_001_143_002_998
token = Application.get_env(:tg, :token)

mp =
  Multipart.new()
  |> Multipart.add_field("chat_id", chat_id_int)
  |> Multipart.add_file("test.txt", name: "document")

Tesla.post("https://api.telegram.org/bot#{token}/sendDocument", mp) # Hangs forever
```

This works fine:

```elixir
alias Tesla.Multipart
chat_id_str = "-1001143002998"
token = Application.get_env(:tg, :token)

mp =
  Multipart.new()
  |> Multipart.add_field("chat_id", chat_id_str)
  |> Multipart.add_file("test.txt", name: "document")

Tesla.post("https://api.telegram.org/bot#{token}/sendDocument", mp)
```

### Expected behavior

I would expect it to either work fine with integers or to throw an error when I try to pass something that is not a string, whichever makes more sense.

### PR DESCRIPTION
**Pull request by ConnorRigby**
I thought i'd tackle this one since https://github.com/teamon/tesla/pull/231/ may or may not be abandoned.

Fixes #230

### CODE REVIEW

**Comment by teamon** [comment]
This looks good!

I'd add some more tests, maybe even for every allowed value.

**Comment by ConnorRigby** [comment]
:+1: will take a second pass to add more tests.

**Comment by ConnorRigby** [comment]
While writing the test for Enumerable, i realized that the argument isn't actually an Enumerable, but `iodata` (binary or charlist). Should the docs be updated to reflect that? A map is actually not really supported.

**Comment by teamon** [comment]
Let's keep it simple and stick to the values we know work 100%

**Comment by ConnorRigby** [comment]
Okay i've updated it one last time to only support `iodata` and stream data. I believe it's ready now :+1:

**Pull request merged**
