### PR TITLE
Update travis.yml

### PR DESCRIPTION
**Pull request by amatalai**
* Added otp-22
* Updated elixir/otp versions to make whole matrix more consistent

### CODE REVIEW

**Comment by teamon** [comment]
@amatalai Any ideas what happened in https://travis-ci.org/teamon/tesla/jobs/536866184 ?

**Comment by amatalai** [comment]
not yet, I should have some time to check it soon

**Comment by amatalai** [comment]
Ok, now I get it. `Code.get_docs/2` used in 2 tests is now deprecated and always returns nil.

Possible solutions:
- Change `Code.get_docs/2` to `Code.fetch_docs/1` on `v1.0.0-compat` branch
- Let `v1.0.0-compat` tests run on elixir 1.6.6 as it was before I tried to change it

**Comment by teamon** [comment]
Ahh I think I had the same issue and decided to keep running it on 1.6

**Comment by amatalai** [comment]
I have reverted it to 1.6 as it's not as important as having otp-22 in matrix

**Pull request merged**
