### PR TITLE
Capture GET query params

### PR DESCRIPTION
**Pull request by pawelduda**
This implements #137

### CODE REVIEW

**Comment by teamon** [comment]
This is awesome, 💃 💃 💃 !

I don't know if you've seen it, but there is a Normalize middleware that unified in/out to/from adapters. Have you though about putting query params extraction inside thhis middleware instead of every adapter?

I also think we should add more unit tests for `capture_query_params/1` function. 

Any reason for limiting query params scraping to `GET` requests only? 
Maybe `capture_query_params/1` could take only the `url` instead of whole `env`? 
(This would make testing easier)

Please let me know if you have any questions.

**Comment by pawelduda** [comment]
All these suggestions make sense, I will take care of these changes as soon as I find some time :+1:.
 
Just one question though, what should be the desired behaviour when someone mixes query params with POST data? How should I capture query params to avoid duplicate keys? Maybe there should be a different key in env variable, just for captured query params, to avoid breaking changes?

**Comment by teamon** [comment]
I suppose the confusion comes from web frameworks that tend to mix query params & data extracted from body. In the HTTP spec, "query" is only the part of URL after "?". HTTP itself does not care much about the body of a request - it can be encoded in many different ways, like `JSON`, `XML` or the one used by standard browser forms `form-urlencoded`. 

You can play with curl and httpbin.org to see what is what:

```
~ λ curl -X POST -v "https://httpbin.org/post?a=123&b=456" -d "a=X&b=Y"
# REQUEST HEADERS
> POST /post?a=123&b=456 HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 7
> Content-Type: application/x-www-form-urlencoded
>
# REQUEST BODY
a=X&b=Y

# RESPONSE HEADERS
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: meinheld/0.6.1
< Date: Mon, 11 Dec 2017 12:02:38 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Powered-By: Flask
< X-Processed-Time: 0.00199604034424
< Content-Length: 443
< Via: 1.1 vegur
<
# RESPONSE BODY
{
  "args": {
    "a": "123",
    "b": "456"
  },
  "data": "",
  "files": {},
  "form": {
    "a": "X",
    "b": "Y"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "7",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.54.0"
  },
  "json": null,
  "origin": "83.19.157.237",
  "url": "https://httpbin.org/post?a=123&b=456"
}
```

httpbin.org returns the query params and body params separately as "args" and "form" JSON keys.

Getting back to your question - since query and body are two different things, even if often treated as one, in case of Tesla's env they are separate so there is no need to worry about them mixing :)

**Comment by pawelduda** [comment]
@teamon Sorry for being absent for so long. I am now back to finish this :)

What I did:
- moved logic for capturing query params into the `Normalize` middleware. While this is an improvement, I am not sure if that logic belongs in this very middleware. Perhaps we could create a separate middleware which only takes care of capturing query params? What do you think?

When it comes to more unit tests, I have basically copied the cases from integration tests but I am currently having trouble with being more creative here. If you have ideas for any specific unit test cases, that you feel are missing, let me know.

I also decided to have the function take the whole env as an argument as I saw, that other modules in `middleware/core.ex` behave in a similar manner. I don't think it impacts testing too much in this case.

**Comment by teamon** [comment]
Welcome back @pawelduda! 

The implementation and tests looks good 🥇 
In the meantime I've started working on 1.0 version (in a `1.0` branch). 
In that branch the Normalize middleware is completely removed, however I'm not yet sure where to fit this PR in the new tesla - I will need some more time to figure this out.

Thanks! (And stay tuned ;))

**Comment by teamon** [comment]
This one is trickier then I thought, there are many cases when things could go wrong. I need some more time to do this properly.

**Comment by teamon** [comment]
I'm still not sure how this one should work, but the current implementation (master) seems to be the easiest to reason about. 

I also don't see much interest in this feature. 
Please feel free to reopen.

**Pull request closed without merging**
