### PR TITLE
Use @typep for option to exclude doc generation

### PR DESCRIPTION
**Pull request by chevinbrown**
@teamon this makes sense to me, but I have very little context about the whole project. 🤜

### CODE REVIEW

**Comment by chevinbrown** [comment]
@teamon I'm closing this. Doesn't feel right, unless you are totally ok and it makes sense for the options to be private.

**Comment by teamon** [comment]
Hmmmmm making the type private would be a breaking change :(

**Comment by chevinbrown** [comment]
Tests still pass. ;)

**Comment by chevinbrown** [comment]
The root issue here is that `@typedoc false` isn't honored. 
This may be an actual elixir-lang issue, which I'll need to investigate and probably fix there...

**Comment by amatalai** [comment]
I think that better solution would be to wrap current `@type` in `if unquote(docs) do`, but without `else` clause

**Comment by teamon** [comment]
This would still be possible breaking change for people using `Tesla.Env.option` type in their own code (with `docs: false`)

**Comment by amatalai** [comment]
hmm, but it's not `Tesla.Env.option`. It's `Foo.option` in module `Foo` with `use Tesla, docs: false` and it looks like bug to add Tesla related stuff to docs when `docs: false` is used.

Also, Elixir itself allows breaking changes when it's necessary to fix bug.
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Compatibility%20and%20Deprecations.md#compatibility-between-elixir-non-major-versions

**Comment by chevinbrown** [comment]
@amatalai @teamon seems like it may be an issue with exdoc...I'll submit a PR (#211) that should provide the correct foundation.

**Pull request closed without merging**
