### PR TITLE
Adriankumpf ak add finch adapter

### PR DESCRIPTION
**Pull request by teamon**

### CODE REVIEW

**Comment by coladarci** [comment]
We are excited to try this out, any idea when a release will be cut for this? Thanks a ton for this!

**Comment by teamon** [comment]
https://github.com/teamon/tesla/releases/tag/v1.4.0 sorry it took soooo long

**Comment by adamu** [comment]
What's the advantage of this over the Mind adapter?

**Comment by IslandUsurper** [comment]
One reason I've heard people recommend Finch over Tesla is that Tesla doesn't do connection pooling and makes a new connection for every request. I'm excited to see if this adapter will increase performance over the Mint adapter if you're going to do a lot of requests.

**Pull request merged**
