### PR TITLE
Add infinity retry option

### PR DESCRIPTION
**Pull request by Ljzn**
Sorry for so long. #201 could not be modified, so I created this. Just formatted code so that it can pass the CI.

### CODE REVIEW

**Comment by teamon** [comment]
Hmmm just by reading the code I don't think this will work - it looks like infinite recursion without ever calling `Tesla.run`

**Comment by Ljzn** [comment]
@teamon  fixed

**Comment by teamon** [comment]
Thanks! Can you think of some tests for this?

**Comment by teamon** [comment]
@Ljzn Can you share some more details what is your specific use case for infinite retries?

**Comment by teamon** [comment]
@Ljzn After giving it a lot of thought and gathering feedback from others I've decided to not include `:infinity` retry option. It is very hard to test and the sole existence of such option might encourage its usage, which is a bad practice in general. As an alternative one can always use a big number like `9999999999` as a retry value.

**Pull request closed without merging**
