### PR TITLE
update deps

### LINKED ISSUE #18: Bump deps, remove git dependency
- ibrowse, it is on hex now
- httparrot, v0.4 has a bug in merging query params, I've sent a PR https://github.com/edgurgel/httparrot/pull/20

### PR DESCRIPTION
**Pull request by princemaple**
close #18 

- [x] ibrowse
- [x] httparrot

### CODE REVIEW

**Comment by teamon** [comment]
I think we should go for the lowest version possible - maybe just `>= 4.0.0` would be fine? (Need to check if the API hasn't changed)

**Comment by princemaple** [comment]
Hmm, I don't think it's a good thing to do. Besides, Elixir community is doing fine with SemVer.
You used to have `tag: v4.2`, I'd go with `~> 4.2`. What do you think?

**Comment by teamon** [comment]
Right, I always forget that `~> 4.2` means `4.x`, not `4.2.x`

👍

**Comment by princemaple** [comment]
@teamon this is ready.

**Pull request merged**
