### PR TITLE
logging maps from json

### PR DESCRIPTION
**Pull request by veverkap**
I ran into an error where I was using the JSON middleware AND the debug logging middleware and it couldn't match on `log_body/2` because there was no method that accepted a Map.

I'm not 100% sure this is the best logging.  I'm just using `inspect`

### CODE REVIEW

**Comment by veverkap** [comment]
@teamon I tweaked a few things, but this should be good to go.

**Comment by teamon** [comment]
@veverkap DebugLogger middleware should be used as the last one - this way it will be run just around adapter and will properly report body.

**Comment by veverkap** [comment]
@teamon how can I do that when I'm dynamically building the client?

```elixir
  defp client do
    case Application.get_env(:cloudinex, :debug) do
      true ->
        Tesla.build_client [{Tesla.Middleware.DebugLogger, %{}}]
      _ -> Tesla.build_client []
    end
  end
```

**Comment by veverkap** [comment]
For example, I'm using Tesla for [cloudinex](https://github.com/veverkap/cloudinex) and I want to offer debug logger from Tesla as a configurable setting in my library.

So I use `Application.get_env` to get the debug key and then build the client dynamically:

https://github.com/veverkap/cloudinex/blob/master/lib/cloudinex.ex#L418-L423

However, when do that, I get the following error:

```
15:42:08.720 [debug] < x-xss-protection: 1; mode=block
** (FunctionClauseError) no function clause matching in Tesla.Middleware.DebugLogger.log_body/2
        (tesla) lib/tesla/middleware/logger.ex:64: Tesla.Middleware.DebugLogger.log_body(%{"bandwidth" => %{"limit" => 6442450944, "usage" => 3019695, "used_percent" => 0.05}, "derived_resources" => 156, "last_updated" => "2017-08-24", "objects" => %{"limit" => 125000, "usage" => 208, "used_percent" => 0.17}, "plan" => "Free", "requests" => 208, "resources" => 52, "storage" => %{"limit" => 2671771648, "usage" => 20022771, "used_percent" => 0.75}, "transformations" => %{"limit" => 7500, "usage" => 18, "used_percent" => 0.24}}, "> ")
       (elixir) lib/map.ex:646: Map.update!/3
    (cloudinex) lib/cloudinex.ex:29: Cloudinex.usage/0
```

If I remove debugging, it deserializes it fine.

**Comment by teamon** [comment]
@veverkap Please take a look at #104. In your case it would be

```ex
  defp client do
    case Application.get_env(:cloudinex, :debug) do
      true ->
        Tesla.build_client [], [{Tesla.Middleware.DebugLogger, %{}}]
      _ -> Tesla.build_client []
    end
  end
```

**Comment by teamon** [comment]
@veverkap Hey, have you got a chance to take a look at my last comment?

**Comment by veverkap** [comment]
@teamon yeah, that didn't end up helping, but I just don't use the logger now :)

**Comment by teamon** [comment]
Ok, I'm closing this one then since the new pre/post middleware options allow to inject DebugLogger right before adapter. 

@veverkap Feel free to reopen/comment when you stumble upon any other obstacles.

**Pull request closed without merging**
