### PR TITLE
Add ability to add part without field or content disposition.

### PR DESCRIPTION
**Pull request by ijcd**
I have need for more careful control over the headers and content within the the parts.

### CODE REVIEW

**Comment by teamon** [comment]
👍 

Could you edit the commit so it does not include changes to the `mix.lock`?

**Comment by ijcd** [comment]
Oops, yes. One moment.

--Ian

**Comment by teamon** [comment]
Thanks!

One question - was the changes to existing tests necessary? I'd feel much more confident if there were left as is to ensure this PR does not break existing code in any way.

**Comment by ijcd** [comment]
Well, the tests were rather ad hoc before when I created them. These were
updated to more carefully reflect the spec I was following.

The best thing to do would be to confirm against a few implementations. I
was looking around for some ideas but didn't find anything yet.

I had the same concern though.

I'll review this again.

--Ian

**Comment by teamon** [comment]
Hey @ijcd, what's the status of this PR?

**Comment by teamon** [comment]
@ijcd ping

**Comment by teamon** [comment]
@ijcd I'm going to close this PR due to inactivity. Please feel free to reopen when needed

**Pull request closed without merging**
